services:
  postgres:
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_POSTGRES_CPUS:-0}"
          memory: "${DOCKER_POSTGRES_MEMORY:-0}"
    environment:
      - "POSTGRES_DB=${DB_NAME:-ah_ad_miner_backend}"
      - "POSTGRES_USER=${DB_USER:-ah_ad_miner_backend}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD:-SuperSecureSecret@123}"
    image: "postgres:14.1-bullseye"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "${DOCKER_POSTGRES_PORT_FORWARD:-127.0.0.1:5432}:5432"
    command: postgres -c max_connections=300
    stop_grace_period: "3s"
    healthcheck:
      test: "${DOCKER_POSTGRES_HEALTHCHECK_TEST:-pg_isready -U ah_ad_miner_backend}"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_REDIS_CPUS:-0}"
          memory: "${DOCKER_REDIS_MEMORY:-0}"
    environment:
      - "REDIS_PASSWORD=${REDIS_PASSWORD:-SuperSecureSecret@123}"
    image: "redis:7-alpine"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "${DOCKER_REDIS_PORT_FORWARD:-127.0.0.1:6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-SuperSecureSecret@123} --maxmemory 256mb --maxmemory-policy allkeys-lru
    stop_grace_period: "3s"
    healthcheck:
      test: "${DOCKER_REDIS_HEALTHCHECK_TEST:-redis-cli --no-auth-warning -a $REDIS_PASSWORD ping | grep PONG}"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - "redis:/data"
volumes:
  postgres: {}
  redis: {}
